name: toSilverDeploy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Get changed files
            id: changed-files
            uses: tj-actions/changed-files@v35
            with:
              since_last_remote_commit: true
              separator: ","
          - name: Deploy
            uses: appleboy/scp-action@v1
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              port: ${{ secrets.SSH_PORT }}
              source: "**"
              target: /www/wwwroot/zocsrd/__node_project/mail/
          - name: Dependencies
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              port: ${{ secrets.PORT }}
              script: |
                cd /www/wwwroot/zocsrd/__node_project/mail/
                npm install
                echo ok